# Mihomo / Clash Configuration
# Please replace with your own configuration
mixed-port: 7890
allow-left: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090

proxies:
  # - name: "example"
  #   type: ss
  #   server: server
  #   port: 443
  #   cipher: aes-256-gcm
  #   password: password

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - DIRECT
      # - example

rules:
  - MATCH,PROXY
